FROM openjdk:17
LABEL maintainer="itsupport@gmail.com"
ADD target/bc-stock-finhub-0.0.1-SNAPSHOT.jar bc-stock-finhub-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java", "-jar","bc-stock-finhub-0.0.1-SNAPSHOT.jar"]
EXPOSE 8085